name: mogat_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - cuda=11.6.2
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=11.8.86
  - cuda-libraries=11.6.2
  - cuda-libraries-dev=11.6.2
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.6.2
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.6.2
  - cuda-tools=11.6.2
  - cuda-visual-tools=11.6.2
  - cycler=0.11.0
  - dbus=1.13.18
  - ffmpeg=4.3
  - fftw=3.3.9
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - future=0.18.2
  - gds-tools=1.4.0.31
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libclang=10.0.1
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.37
  - libpq=12.9
  - libtasn1=4.16.0
  - libunistring=0.9.10
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nsight-compute=2022.3.0.22
  - nspr=4.33
  - nss=3.74
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.2.5
  - pcre=8.45
  - pip=22.2.2
  - ply=3.11
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.7
  - python-dateutil=2.8.2
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - requests=2.28.1
  - seaborn=0.12.1
  - setuptools=65.5.0
  - six=1.16.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.12
  - wheel=0.37.1
  - zstd=1.5.2
  - pip:
    - et-xmlfile==1.1.0
    - install==1.3.5
    - jinja2==3.1.2
    - joblib==1.2.0
    - markupsafe==2.1.1
    - openpyxl==3.0.10
    - pickle5==0.0.12
    - pyg-lib==0.1.0+pt113cu116
    - pyreadr==0.4.7
    - scikit-learn==1.0.2
    - threadpoolctl==3.1.0
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.1.0+pt113cu116
    - torch-sparse==0.6.15+pt113cu116
    - tqdm==4.64.1
    - xgboost==1.6.2